version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c 'until nc -z db 5432; do
               echo "Esperando la base de datos...";
               sleep 1;
             done;
             gunicorn --bind 0.0.0.0:8000 --timeout 120 djangoApp.wsgi:application'
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /var/lib/jenkins/workspace/django_rest_app_template_start/staticfiles:/app/staticfiles  # Monta la carpeta estática en el host
      - /var/lib/jenkins/workspace/django_rest_app_template_start/media:/app/media  # Monta la carpeta de archivos multimedia en el host
    ports:
      - "8001:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - django_rest_app_template_start_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  django_rest_app_template_start_postgres_data:
